metan/urls.py
from django.conf.urls import include,url
from django.contrib import admin
#from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^mtnlss/', include('mtnlss.urls')),
    url(r'^', include('mtnlss.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

mtnlss/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^proj/$', views.proj),
    url(r'^projslist/$', views.projsList),
    url(r'^addproj/$', views.addProj),
    url(r'^paper/(?P<paperID>.+)/$', views.paper),
    url(r'^editprojtitle/(?P<projID>.+)/$', views.editProjTitle),
    url(r'^addpaper/(?P<projID>.+)/$', views.addPaper),
    url(r'^deleteproj/(?P<projID>.+)/$', views.deleteProj),
    url(r'^paperslist/(?P<returnInvalidForm>.+)/(?P<projID>.+)/$', views.papersList),
    url(r'^deletepaper/(?P<paperID>.+)/$', views.deletePaper),
    url(r'^addquestion/(?P<projID>.+)/$', views.addQuestion),
    url(r'^questionslist/(?P<returnInvalidForm>.+)/(?P<projID>.+)/$', views.questionsList),
    url(r'^deletequestion/(?P<questionID>.+)/$', views.deleteQuestion),
    url(r'^deletevars/(?P<projID>.+)/$', views.deleteVars),
    url(r'^addgroupvar/(?P<projID>.+)/$', views.addGroupVar), 
    url(r'^editvarname/(?P<projID>.+)/$', views.editVarName),
    url(r'^analysisfirstpage/(?P<projID>.+)/$', views.analysisFirstPage, name='analysisfirstpage'),
    url(r'^analysisresult/(?P<projID>.+)/$', views.analysisResult, name='analysisresult'),
    url(r'^exportPapers/$', views.exportPapers, name='exportPapers'),
    url(r'^importfromfile/$', views.importFromFile, name='importfromfile'),
    url(r'^metaanalysisfirstpage/(?P<projID>.+)/$', views.metaAnalysisFirstPage, name='metaanalysisfirstpage'),
    url(r'^metaanalysisresult/(?P<projID>.+)/$', views.metaAnalysisResult, name='metaanalysisresult'),
    url(r'^metaanalysisresultasfile/(?P<projID>.+)/$', views.metaAnalysisResultAsFile, name='metaanalysisresultasfile'),
    
    url(r'^addNewVariable/(?P<paperID>.+)/$', views.addNewVariable),
    url(r'^addExistingVariable/(?P<paperID>.+)/$', views.addExistingVariable),
    url(r'^corTable/(?P<paperID>.+)/$', views.corTable),   
    url(r'^detatchVariable/(?P<paperID>.+)/$', views.detatchVariable),
    url(r'^moverow/(?P<paperID>.+)/$', views.moveRow),
    url(r'^gethiddendivs/(?P<paperID>.+)/$', views.getHiddenDivs),
    url(r'^savecorrelations/(?P<paperID>.+)/$', views.saveCorrelations),
    url(r'^editpaper/(?P<paperID>.+)/$', views.editPaper),
    url(r'^editanswers/(?P<paperID>.+)/$', views.editAnswers),
]

mtnlss/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_init

class Project(models.Model):
    title = models.CharField(max_length=540)
    admins = models.ManyToManyField(User)
    class Meta:
        ordering = ('id',)
    def getPapersSummary(self):
        result = ""
        counter = 0
        for paper in self.paper_set.all():
            counter += 1
            if counter>3:
                break
            result += "\""+paper.getShortName()+"\""+", "
        if len(result)==0:
            return result
        else:
            return result+"..."
            
class Variable(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=540)
    isgroup = models.BooleanField(default=False)
    variables = models.ManyToManyField("self")    #Only for group variables
    description = models.CharField(max_length=3000, null=True) #Only for group variables
    def getCorrelation(self,v2,p):
        v1 = self
#         if sorted([v1.name,v2.name])[0] != v1:
#             temp = v1
#             v1 = v2
#             v2 = temp
        result = Correlation.objects.filter(paper=p, var1=v1, var2=v2).values_list('value',flat=True)
        if not result:
            result = Correlation.objects.filter(paper=p, var1=v2, var2=v1).values_list('value',flat=True)
        return result
    class Meta:
        unique_together = ('project', 'name',)


class Paper(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=540)
    authors = models.CharField(blank=True,null=True,max_length=540)
    publication = models.CharField(blank=True,null=True,max_length=540)
    year = models.IntegerField(blank=True,null=True)
    sample_size = models.IntegerField(blank=True,null=True)
    variables = models.ManyToManyField(Variable,through='VarPaper', related_name='its_paper')
    def getShortName(self):
        if len(self.title)<20:
            return self.title
        else:
            return self.title[:20]+"..."
    
    def getMidlengthName(self):
        if len(self.title)<60:
            return self.title
        else:
            return self.title[:60]+"..."
        
    def getVarsOrdered(self):
        return self.variables.order_by('varpaper__order')
    
    class Meta:
        ordering = ('id',)


class Question(models.Model):
    text = models.CharField(max_length=540)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    class Meta:
        ordering = ('id',)

class Answer(models.Model):
    value = models.CharField(blank=True,null=True,max_length=540)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    class Meta:
        unique_together = ('question', 'paper',)

    
class VarPaper(models.Model):
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    var = models.ForeignKey(Variable, on_delete=models.CASCADE)
    order = models.IntegerField()
    mean = models.DecimalField(blank=True,null=True,decimal_places=4,max_digits=15)
    sd = models.DecimalField(blank=True,null=True,decimal_places=4,max_digits=15)
    alpha = models.DecimalField(blank=True,null=True,decimal_places=4,max_digits=15)
    class Meta:
        unique_together = ('var', 'paper',)

# def extraInitForCorrelation(**kwargs):
#     #This should be run every time the constructor of Correlation is called to make sure that
#     #var1 refers to the variable that is alphabetically before the other one
#     var1 = kwargs['kwargs'].get('var1')
#     var2 = kwargs['kwargs'].get('var2')
#     if sorted([var1.name,var2.name])[0] != var1:
#         temp = var1
#         var1 = var2
#         var2 = temp

class Correlation(models.Model):
    #For paper p, what is the correlation between var1 and var2
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    value = models.DecimalField(blank=True,null=True,decimal_places=4,max_digits=10)
    var1 = models.ForeignKey(Variable, on_delete=models.CASCADE, related_name="var1")
    var2 = models.ForeignKey(Variable, on_delete=models.CASCADE, related_name="var2")
    

mtnlss/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import *
from mtnlss.forms import *
from mtnlss.models import *
from django.forms import inlineformset_factory
from django.http import HttpResponse
from viewHelpers import *
from sqlite3 import ProgrammingError
from django.db import transaction
import math
import csv
import re
from timeit import default_timer as timer


@login_required
def home(request):
    newProjForm = ProjectForm()
    return render(request, 'mtnlss/home.html',{'newProjForm':newProjForm})

@login_required
def proj(request):
    #called when the proj page is loaded
    form = None
    newPaperform = PaperForm()
    if request.method == 'GET':
        projID = request.GET['id']
        theProj = Project.objects.get(pk=projID)
        form = ProjectForm(instance=theProj)
    else:
        form = ProjectForm()
        
    return render(request, 'mtnlss/proj.html', {'form': form,'newPaperForm':newPaperform})

@login_required
def addProj(request):
    form = ProjectForm(request.POST)
    
    if form.is_valid():
        data = form.cleaned_data
        title = data['title']
        theProj = Project(title=title)
        theProj.save()
        theProj.admins.add(request.user)
        theProj.save()
        return HttpResponse("Done")
    else:
        return HttpResponse("Error")

@login_required
def projsList(request):
#     allProjs = Project.objects.all()
    try:
        allProjs = request.user.project_set.all()
    except:
        allProjs = []
    return render(request, 'mtnlss/projsList.html',{'projs':allProjs})

@login_required
def editProjTitle(request,projID):
    theProj = Project.objects.get(pk=projID)
    form = ProjectForm(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        title = data['title']
        theProj.title = title
        theProj.save()
        return HttpResponse("Done")
    else:
        return HttpResponse("Error")

@login_required
def addPaper(request,projID):
    #Called when the user presses 'save' to add a new paper
    form = PaperForm(request.POST)
    if form.is_valid():
        thePaper = form.instance
        thePaper.project = Project.objects.get(pk=projID)
        thePaper.save()
        return papersList(request,"no",projID)
    else:
        return papersList(request,"yes",projID)


@login_required
def papersList(request, returnInvalidForm, projID):
    #called whenever the papersList in the proj page is loaded or refreshed
    theProj = Project.objects.get(pk=projID)
    newPaperForm = None
    if returnInvalidForm == "no":
        newPaperForm = PaperForm()
    else:
        newPaperForm = PaperForm(request.POST)
    return render(request,'mtnlss/papersList.html', {'project': theProj,'newPaperForm':newPaperForm})


@login_required
def deletePaper(request,paperID):
    try:
        Paper.objects.filter(id=paperID).delete()
        return HttpResponse("Done")
    except:
        return HttpResponse("Error")

@login_required
def deleteProj(request,projID):
    try:
        Project.objects.filter(id=projID).delete()
        return HttpResponse("Done")
    except:
        return HttpResponse("Error")

@login_required
def questionsList(request,returnInvalidForm,projID):
    #called whenever the QuestionsList in the proj page is loaded or refreshed
    theProj = Project.objects.get(pk=projID)
    newQuestionForm = None
    if returnInvalidForm == "no":
        newQuestionForm = QuestionForm()
    else:
        newQuestionForm = QuestionForm(request.POST)
    return render(request,'mtnlss/questionsList.html', {'project': theProj,'newQuestionForm':newQuestionForm})

@login_required
def addQuestion(request,projID):
    #Called when the user presses 'save' to add a new paper
    form = QuestionForm(request.POST)
    if form.is_valid():
        theQ = form.instance
        theQ.project = Project.objects.get(pk=projID)
        theQ.save()
        return questionsList(request,"no",projID)
    else:
        return questionsList(request,"yes",projID)
    
@login_required
def deleteQuestion(request,questionID):
    try:
        Question.objects.filter(id=questionID).delete()
        return HttpResponse("Done")
    except:
        return HttpResponse("Error")
@login_required
@login_required
def paper(request, paperID):
    #Called when the paper page (the JS box) is loaded
    p = Paper.objects.get(pk=paperID)
    form = PaperForm(instance=p)
    answersForm = AnswersForm(p)
    varsHiddenCode = getVarsDivCode(paperID)
    corsHiddenCode = getCorsDivCode(paperID)
    return render(request, 'mtnlss/paper.html', {'form': form,'hiddenCode':varsHiddenCode+corsHiddenCode, 'answersForm':answersForm})

@login_required
def corTable(request,paperID):
    p = Paper.objects.get(pk=paperID)
    vars = p.getVarsOrdered()
    thisPaperVarsIDs = vars.values_list('id',flat=True)
    otherProjVars = Variable.objects.filter(project=p.project).exclude(id__in=thisPaperVarsIDs)
    varForm = VariableForm()
    return render(request, 'mtnlss/corTable.html', {'varCount':range(len(vars)), 'otherProjVars': otherProjVars, 'varForm':varForm, 'varsLen':len(vars)});

@login_required
def addExistingVariable(request,paperID):
    varID = request.POST.get('thevar')
    addExistingVariableToDB(varID,paperID)
    hiddenDiv = getHiddenDivs(request, paperID)
    return HttpResponse(hiddenDiv)
    
@login_required
def addNewVariable(request,paperID):
    varForm = VariableForm(request.POST)
    if varForm.is_valid():
        n = varForm.cleaned_data['name']
        p = Paper.objects.get(pk=paperID)
        newVar = Variable(name=n, project=p.project)
        newVar.save()
        addExistingVariableToDB(newVar.id,paperID)
        hiddenDiv = getHiddenDivs(request, paperID)
        return HttpResponse(hiddenDiv)
    else:
        return HttpResponse("Error")
    
@login_required
def detatchVariable(request,paperID):
    p = Paper.objects.get(pk=paperID)
    v = Variable.objects.get(pk=request.POST["varid"])
    vp = VarPaper.objects.filter(paper=p,var=v)
    vp.delete()
    return HttpResponse("Done")
    
@login_required
def moveRow(request,paperID):
    #Swaps the "order"s for the two Variable objects in their relation to the current paper
    p = Paper.objects.get(pk=paperID)
    otherV = Variable.objects.get(pk=request.POST["otherid"])
    thisV = Variable.objects.get(pk=request.POST["thisid"])
    thisvp = VarPaper.objects.filter(paper=p,var=thisV)[0]
    othervp = VarPaper.objects.filter(paper=p,var=otherV)[0]
    temp = thisvp.order
    thisvp.order = othervp.order
    othervp.order = temp
    thisvp.save()
    othervp.save()
    return HttpResponse("Done")
    
@login_required
def getHiddenDivs(request,paperID):
    corsCode = getCorsDivCode(paperID)
    varsCode = getVarsDivCode(paperID)
    return HttpResponse(corsCode+varsCode)
    
@login_required
def saveCorrelations(request,paperID):
    try:
        p = Paper.objects.get(pk=paperID)
        corsInDB = Correlation.objects.filter(paper=p)
        updatedSomething = False
        handledKeys = {}
        #Iterate through the Correlation objects for this paper, for each one find the new value we just got from the user, and update it.
        for c in corsInDB:
            key1 = str(c.var1.id)+"_"+str(c.var2.id)
            key2 = str(c.var2.id)+"_"+str(c.var1.id)
            theKey = None
            if key1 in request.POST:
                theKey = key1
            elif key2 in request.POST:
                theKey = key2
            else:
                continue
            handledKeys.update({theKey:""})
            newCorValue = request.POST[theKey]
            if newCorValue=="":
                c.delete()
                updatedSomething = True
                continue
            try:
                newCorValue = Decimal(newCorValue)
                if(c.value != newCorValue):
                    c.value = newCorValue
                    c.save()
                    updatedSomething = True
            except: 
                return HttpResponse("Error")
        #Now look for correlations that are being added for the first time and therefore don't have a Correlation object in the DB
        for k in request.POST:
            if not k in handledKeys:
                updatedSomething = True
                newVal = request.POST[k]
                if k.startswith("mean") or k.startswith("sd") or k.startswith("alpha"):
                    [type,varid] = k.split("_")
                    v = Variable.objects.get(pk=varid)
                    varpaper = VarPaper.objects.filter(var=v,paper=p)[0]
                    if type=="mean":
                        varpaper.mean = newVal
                    if type=="sd":
                        varpaper.sd = newVal
                    if type=="alpha":
                        varpaper.alpha = newVal    
                    varpaper.save()  
                else: 
                    [varid1,varid2] = k.split("_")
                    v1 = Variable.objects.get(pk=varid1)
                    v2 = Variable.objects.get(pk=varid2)
                    newC = Correlation(paper=p,value=newVal,var1=v1,var2=v2)
                    newC.save()
        
        if updatedSomething:
            return HttpResponse("Done")
        else:
            return HttpResponse("nochange")
    except Exception as e:
        print(e)
        return HttpResponse("Error")
        
@login_required
def editPaper(request,paperID):
    existingData = Paper.objects.filter(id=paperID).values()[0]
    existingVersion = Paper.objects.get(pk=paperID)
    form = PaperForm(request.POST)
    if form.is_valid():
        form = PaperForm(request.POST, initial=existingData)
        if not form.has_changed():
            return HttpResponse("nochange")
        else:
            form = PaperForm(request.POST, instance=existingVersion)
            form.save()
            return HttpResponse("Done")
    else:

templates/mtnlss/analysisFirstPage.html
{% extends 'mtnlss/base.html' %}

{% block include_js %}
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/analysis.js' %}" ></script>
<link rel="stylesheet" type="text/css" href="{% static 'analysis-style.css' %}" />
{% endblock %}

{% block title %}Analysis{% endblock %}



{% block content %}
<div id='chooseAnalVarsBox' class='boxOuter'>
	<div class='topRibbon'>Select Variables</div>
	<div id='chooseAnalVarsBoxInside' class='boxInner'>
		<div id='userGuide'>Please choose the variables you want to use for the analysis.</div>
		<form action="/analysisresult/{{project.id}}/" method="POST" id="prepareAnalysisForm"> 
			{% csrf_token %}
			<table id='analFPTable'>
			<tr>
				<td class='analFPtd'>
					<div>Group 1:</div>
					<select name='group1' multiple size=20 class='chooseAnalVarSelect' id='chooseAnalVarSelect1'></select>
					<div><input type='button' id='analFPRemoveVar' value='Remove Selected' onClick='removeFromBox(1)'></input></div>
					<div>
						<select class='analFPDropdown' id='dropdown1'>
							{% for v in project.variable_set.all %}
								<option value="{{v.id}}">{{v.name}}</option>
							{% endfor %}
						</select>
					</div>
					<div><input type='button' value='Add' onClick='addToBox(1)' style='float:left;'></input></div>
					<div><input type='button' value='Add all' onClick='addAllToBox(1)' style='float:right;'></input></div>
				</td>
				<td class='analFPtd'>
					<div>Group 2:</div>
					<select name='group2' multiple size=20 class='chooseAnalVarSelect' id='chooseAnalVarSelect2'></select>
					<div><input type='button' id='analFPRemoveVar' value='Remove Selected' onClick='removeFromBox(2)'></input></div>
					<div>
						<select class='analFPDropdown' id='dropdown2'>
							{% for v in project.variable_set.all %}
								<option value="{{v.id}}">{{v.name}}</option>
							{% endfor %}
						</select>
					</div>
					<div><input type='button' value='Add' onClick='addToBox(2)' style='float:left;'></input></div>
					<div><input type='button' value='Add all' onClick='addAllToBox(2)' style='float:right;'></input></div>
				</td>
			</tr>
			</table>
			<div class='getSigBox'>
				<div class='getSigLabel'>Significance Level, <b>Confidence</b> Intervals (%):</div>
				<input class='getSigTextfield' name='sig1' size=2 type='textfield' value=95></input>
			</div>
			<div class='getSigBox'>
				<div class='getSigLabel'>Significance Level, <b>Credibility</b> Intervals (%):</div>
				<input class='getSigTextfield' name='sig2' size=2 type='textfield' value=80></input>
			</div>
			<div id='finalAnalyzeButtonContainer'><input type='submit' id='finalAnalyzeButton' value='Analyze'></input></div>
		</form>
	</div>
</div>

<div style='visibility:hidden' id='hiddenDiv'>
{% for id,name in varsDict.items %}
	<div class='hiddenVar' id='{{id}}'>{{name}}</div>
{% endfor %}
</div>

{% endblock %}

templates/mtnlss/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

{% block include_js %}{% endblock %}

<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
	{% include "mtnlss/headerBar.html" %}
	  
	  <div class='contentDiv'>
	  	{% block content %}{% endblock %}
	  </div>
    
</body>
</html>

templates/mtnlss/metaAnalysisFirstPage.html
{% extends 'mtnlss/base.html' %}

{% block include_js %}
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/analysis.js' %}" ></script>
<link rel="stylesheet" type="text/css" href="{% static 'analysis-style.css' %}" />
{% endblock %}

{% block title %}Meta-Analysis Table{% endblock %}



{% block content %}
<div class='boxOuter'>
	<div class='topRibbon'>Select Variables</div>
	<div class='boxInner'>
		<div id='userGuide'>Please choose the variables you want to use for the meta-analysis table.</div>
		<form action="/metaanalysisresult/{{project.id}}/" method="POST" id="prepareMetaAnalysisForm"> 
			{% csrf_token %}

			<table style='margin: 0 auto;'><tr><td>
				<select name='group1' multiple size=20 class='chooseAnalVarSelect' id='chooseAnalVarSelect3'></select>
				<div><input type='button' id='analFPRemoveVar' value='Remove Selected' onClick='removeFromBox(3)'></input></div>
				<div>
					<select class='analFPDropdown' id='dropdown3'>
						{% for v in project.variable_set.all %}
							<option value="{{v.id}}">{{v.name}}</option>
						{% endfor %}
					</select>
				</div>
				<div>
					<div><input type='button' value='Add' onClick='addToBox(3)' style='float:left;'></input></div>
					<div><input type='button' value='Add all' onClick='addAllToBox(3)' style='float:right;'></input></div>
				</div>
			</td></tr></table>
			<div class='getSigBox'>
				<div class='getSigLabel'>Significance Level, <b>Confidence</b> Intervals (%):</div>
				<input class='getSigTextfield' name='sig1' size=2 type='textfield' value=95></input>
			</div>
			<div class='getSigBox'>
				<div class='getSigLabel'>Significance Level, <b>Credibility</b> Intervals (%):</div>
				<input class='getSigTextfield' name='sig2' size=2 type='textfield' value=80></input>
			</div>
			<br>
			<div  style='margin: 0 auto; width: 178px;'><input type='submit' id='finalMetaAnalyzeButton' value='Generate Meta-Analysis Table'/></div>
		</form>
	</div>
</div>

<div style='visibility:hidden' id='hiddenDiv'>
{% for id,name in varsDict.items %}
	<div class='hiddenVar' id='{{id}}'>{{name}}</div>
{% endfor %}
</div>

{% endblock %}

templates/mtnlss/proj.html
{% extends 'mtnlss/base.html' %}

{% block include_js %}
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
<script type="text/javascript" src="{% static 'js/proj.js' %}" ></script>
<link rel="stylesheet" type="text/css" href="{% static 'proj-style.css' %}" />
{% endblock %}

{% block title %}
	{{ form.instance.title }}
{% endblock %}

{% block content %}
	<span id='proj_id_div' style='visibility:hidden'>{{form.instance.id}}</span>
	<div class="projEditDiv" style='float:left'>
	<form action="/whatever/" method="POST" id="projEditForm">
    	{% csrf_token %}
		<div class='projLabel'>{{ form.title }}</div>
		<div class='editProjTitleLabel' onClick='enableProjTitle()'>
			<img src='{% static 'images/edit.png' %}' style="width:12px;"></img>
			<span style='cursor: pointer'> Edit title</span>
		</div>
		<input id='saveProjTitleChangeButton' type="submit" value="Save" /><input type='button' id='cancelProjTitleChangeButton' onClick='disableProjTitle()' value='Cancel'/>
	</form>
	</div>
	<span class='analButtons' id='analyzeButton'><a href='{% url 'analysisfirstpage' projID=form.instance.id %}'>Analysis</a></span>
	<span class='analButtons' id='metaanalyzeButton' style='margin-right: 10px;'><a href='{% url 'metaanalysisfirstpage' projID=form.instance.id %}'>Meta-analysis Table</a></span>
	<br><br><br><br>
	<div id='projPageTopContainer'>
		<div id='questionsListBox'>
			<!-- JS code brings the code from extraQuestionsList here -->
		</div>
		<div id="variableBox" class='boxOuter'>
			<div  class='topRibbon'>
			Variables: <span class='numberLabel'>{{form.instance.variable_set.count}} </span>
			</div>
			<div class='boxInner'>
				<div id='varsScrollBox'>
				{% for var in form.instance.variable_set.all %}
					{% if var.isgroup %}
						<span class='varLabel' id='varLabel_{{var.id}}' title="{{var.description}}" onClick='selectVar({{var.id}})'>
						<span class='varEditButton' onClick='editVarNameClicked({{var.id}})'><img src='{% static 'images/edit.png' %}' style="width:8px;"></img></span>
						<input class='varLabeltf varLabelGroup' id='varLabeltf_{{var.id}}' data-initialVal='{{var.name}}' type='textfield' value='{{var.name}}'></input>
					{% else %}
						<span class='varLabel' id='varLabel_{{var.id}}' onClick='selectVar({{var.id}})'>
						<span class='varEditButton' onClick='editVarNameClicked({{var.id}})'><img src='{% static 'images/edit.png' %}' style="width:8px;"></img></span>
						<input class='varLabeltf' id='varLabeltf_{{var.id}}' data-initialVal='{{var.name}}' type='textfield' value='{{var.name}}'></input>
					{% endif %}
					</span>
				{% endfor %}
				</div>
				
				<div id='varBoxFooter'>
					<input style='float:right; margin-left:10px;' type='button' value='Delete Selected Variables' onClick='deleteSelectedVars()'></input>
					<input style='float:right' type='button' value='Create Group Variable from Selected Variables' onClick='addGroupVar()'></input>
				</div>
			</div>
		</div>
	</div>
	
	<div class='boxOuter' id='papersListBox'>
		<!-- JS code brings the code from PapersList here -->
	</div>
	
	<div id='darkLayer'></div>
	<div id='paperPopup'></div>
	<div id="waitingImage"><img style='float: left; margin-right: 4px; margin-top: 5px;' src="{% static 'images/ajax-loader.gif' %}"></div>
{% endblock %}

templates/mtnlss/projsList.html
{% load static %}


<table class= "projsTable" style='border-collapse: collapse; width: 655px; border-bottom:1px solid #ccc;'>
<th> Project<td style='text-align: center'><b>Papers</b></td> <td  style='text-align: center;'><b>Variables</b></td> </th>
	{% for proj in projs %}
	<tr class="{% if forloop.counter|divisibleby:2 %}evenRow{% else %}oddRow{% endif %}" style='border-top: 1px #ccc solid;'>
		<td style='min-width:130px;'><a href="/mtnlss/proj?id={{proj.id}}">{{proj.title}}</a></td>
		<td style='min-width:190px;'>{{proj.paper_set.count}}<span class="sampleItems">&nbsp;&nbsp;({{proj.getPapersSummary}})</span></td>
		<td style='width:70px'>{{proj.variable_set.count}}</td>
		<td class='deleteProjTD' style='width:10px' title='Delete project' onClick='deleteProj({{proj.id}})'><img src='{% static 'images/delete.ico' %}' style="width:15px;"></img></td>
	</tr>
	{% endfor %}
</table>